### ISSUE TITLE
Why is the hint loss not implemented in the code?

### ISSUE THREAD

**Issue by Wenju-Huang** [SsisyphusTao/SSD-Knowledge-Distillation#3]

**Comment by SsisyphusTao** [comment]
Actually, it is implemented here, in nets/multibox_loss.py. I didn't implement the method described in paper literally, because it didn't work...

![image](https://user-images.githubusercontent.com/47047345/94510284-f9fde900-0248-11eb-9edc-4c083fcbde6c.png)
